### ISSUE TITLE
Cannot unpack with npm run dev

### ISSUE THREAD

**Issue by GianniErrera** [JeffreyWay/laravel-mix-tailwind#7]
For a couple of days I have been trying to unpack Tailwind from Webmix following the steps detailed in the info, but something always goes wrong.
Down here I am pasting the error log.

I should mention that npm version is currently 6.9.0
I have tried to clear cache, delete node_modules foilder and then reinstall npm install; nothing has worked so far, so I resolved to open a thread here.

```
> @ development Path
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
Path\node_modules\tailwindcss\lib\lib\registerConfigAsDependency.js:9
    throw new Error(`Specified Tailwind config file "${configFile}" doesn't exist.`);
    ^



Error: Specified Tailwind config file "Path\tailwind.js" doesn't exist.
    at exports.default (Path\node_modules\tailwindcss\lib\lib\registerConfigAsDependency.js:9:11)
    at _postcss2.default.plugin.config (Path\node_modules\tailwindcss\lib\index.js:37:59)
    at creator (Path\node_modules\tailwindcss\node_modules\postcss\lib\postcss.js:133:35)
    at Tailwind.boot (Path\node_modules\laravel-mix-tailwind\index.js:25:29)
    at Mix.listen (Path\node_modules\laravel-mix\src\components\ComponentFactory.js:56:41)
    at events.(anonymous function).forEach.handler (Path\node_modules\laravel-mix\src\Dispatcher.js:34:47)
    at Array.forEach (<anonymous>)
    at Dispatcher.fire (Path\node_modules\laravel-mix\src\Dispatcher.js:34:28)
    at Mix.dispatch (Path\node_modules\laravel-mix\src\Mix.js:113:25)
    at Object.<anonymous> (Path\node_modules\laravel-mix\setup\webpack.config.js:19:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     Path\Users\User\AppData\Roaming\npm-cache\_logs\2019-03-07T18_47_51_190Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    Path\User\AppData\Roaming\npm-cache\_logs\2019-03-07T18_47_51_512Z-debug.log
```

**Comment by GianniErrera** [comment]
Nevermind, I had to init the config file and rebuild node-sass
